### ISSUE TITLE
incompatibility with vanilla hammers/excavators 

### ISSUE THREAD

**Issue by Nathan22211** [CottonMC/FunctionAPI#1]
the tags don't activate when blocks are broken by a hammer nor excavators

**Comment by Frontrider** [comment]
I run the events when the block's `onBroken` method is called. Can you reference this issue to him? If I need another hook somewhere I'll gladly add, but if he does something unexpected, then I can't help it.

It works fine for vanilla tools.

**Comment by Frontrider** [comment]
Found it. Fixing it now.

**Comment by Frontrider** [comment]
I love this game. It can break a block in 2 specific ways, that do not overlap. Handling booth now.
