### ISSUE TITLE
Pistons do not trigger any block events

### ISSUE THREAD

**Issue by crysthala** [CottonMC/FunctionAPI#11]
**Describe the bug**
None of the events I tested were fired when a test block was moved with a piston. Neither sticky nor regular pistons appeared to work.

**To Reproduce**
1. I created tags for each of the following events: `activate`, `placed`, `set`, `broken`, `stepped_on`, `entity_collided`, `entity_landed`, `projectile_hit`.
2. I pointed the tags at function files that simply ran `say I was activated` or `say Something touched me` to indicate which of the events were firing.
3. I placed the test block in the world (it said `"I was placed"`) and attempted to move it with pistons. The block was moved as expected, but none of the events fired.
4. All the events fired in their other expected circumstances, ex. dropping a falling block or entity on it, walking on it, shooting an arrow at it, etc. I didn't see any errors in the log.

**Version of the (please complete the following information):**
 - Mod: 1.2.2
 - Fabric API: 0.4.0+build.240
 - Minecraft: 1.14.4

**Additional context** *Optional*
The test block in question was created with Block Factory. Don't know if that's relevant.

**Comment by Frontrider** [comment]
The source of the block does not matter.

**Comment by Frontrider** [comment]
I know how pistons move stuff, it's going to be a pain.

**Comment by Frontrider** [comment]
And it was less of a pain than expected, but still very stupid.
