### ISSUE TITLE
Block activate events firing twice with a single click

### ISSUE THREAD

**Issue by crysthala** [CottonMC/FunctionAPI#12]
**Describe the bug**
When activating a block, the event sometimes fires twice extremely rapidly.

**To Reproduce**
1. Created an `activate` tag for a block
2. Pointed the tag at a function that runs a `say` command to indicate it's been fired, checks to see if `@s` is holding the correct item, and fires a _second_ event if that's the case
3. If the condition is met, the second event is also fired twice.

**Version of the (please complete the following information):**
 - Mod: 1.2.2
 - Fabric API: fabric-api-0.4.0+build.240
 - Minecraft: 1.14.4

**Additional context** *Optional*
Here, have a [latest.log](https://github.com/CottonMC/FunctionAPI/files/3776273/latest.log)

**Comment by Frontrider** [comment]
It fires twice because it happens for both hands! I'm going to add a separate event for the offhand, and the same is going to happen with the item events.

**Comment by Frontrider** [comment]
fixed in dev.
