### ISSUE TITLE
Block activate event not working on Cauldrons

### ISSUE THREAD

**Issue by crysthala** [CottonMC/FunctionAPI#3]
For testing, I have a .json tag pointing to a simple test function `cauldron_test` that should run `say Hi!` whenever the cauldron is right-clicked, but nothing happens. I've double-checked that the paths and filenames, etc. are correct, and the corresponding setup for gravel is working perfectly.

I can't find any error messages in it, but here's a [latest.log](https://github.com/Frontrider/functionapi/files/3694929/latest.log) anyway. Starting up MC, loading a world, placing a cauldron, right-clicking it with several objects. (I apologize for all the Optifine spam.)

I'm really enjoying messing around with this mod, and I appreciate all the work you're putting into it! Many thanks. :)

**Comment by Frontrider** [comment]
Found it, Cauldrons are just not playing nice. Before I release anything, can you try out other blocks that have a right-click functionality by default? Those may also be bugged, along with any block that already does something on my events.

 I can handle them without issues, but I need to know what else might be broken.

**Comment by crysthala** [comment]
Sure, I can do that! Don't mind me, just going to make a little list...
- [x] Lectern
- [x] Composter
- [x] Furnace
- [x] Blast Furnace
- [x] Smoker
- [x] Enchanting Table
- [x] Chest
- [x] Barrel
- [x] Crafting Table
- [x] Cartography Table
- [x] Buttons
- [x] Doors
- [x] Anvils
- [x] Beacon
- [x] Trapdoors
- [x] Beds
- [x] Shulker Boxes
- [x] Brewing Stand
- [x] Daylight Detector
- [x] Dispenser
- [x] Dropper
- [ ] End Portal Frame
- [x] Ender Chest
- [x] Flower Pot
- [x] Grindstone
- [x] Hopper
- [x] Jukebox
- [x] Note Block
- [x] Lever
- [x] Loom
- [x] Comparator
- [x] Repeater
- [ ] Redstone Ore
- [ ] Scaffolding
- [ ] Sea Pickle
- [x] Stonecutter
- [ ] Sweet Berry Bush
- [x] Trapped Chest

I'll test this later tonight and let you know what I find out.

**Comment by Juuxel** [comment]
@Frontrider You can use Fabric's UseBlockCallback instead of mixing into Block.activate.

**Comment by LemmaEOF** [comment]
I found the issue! The mixins for block events are on the `Block` class instead of on `BlockState`, meaning that any `Block` subclass that overrides `activate` without calling super will never call the code.

**Comment by Frontrider** [comment]
I'll be going with the blockState route.

**Comment by crysthala** [comment]
The following interactive blocks are unaffected: Scaffolding, End Portal Frame, Redstone Ore, Sea Pickle, and Sweet Berry Bush. All the blocks above with the checkbox ticked are affected by this or a similar issue, as well as Bells and Campfires, which I missed while making that list. If I forgot any others, please let me know and I'll check them as well.

**Comment by Frontrider** [comment]
Thank you.

**Comment by Frontrider** [comment]
I fixed it in dev, now it should work for every block.
