### ISSUE TITLE
/fill and /setblock not triggering a place event

### ISSUE THREAD

**Issue by Nathan22211** [CottonMC/FunctionAPI#4]
**Describe the bug**
/fill and /setblock aren't triggering their receptive tags for the place event

**To Reproduce**
1. make a tag for a block. I did "extrapieces:block_breaker_stairs since I was doing something with that
2. set a function for it to activate.
3. run a setblock or fill command with the block tagged as the block to be placed

**Expected behavior** *Optional*
the tags should trigger at every block from those 2 commands. in my case I'd see 1024 custom model armor stands after executing it"

**Screenshots** *Optional*

**Version of the (please complete the following information):**
 - Mod. function API 1.1.1
 - Fabric API 0.3.3 build.234
 - Minecraft 1.14.4

**Additional context** *Optional*

**Comment by Frontrider** [comment]
Which method are you using?

**Comment by Frontrider** [comment]
I'm only making it clear for cases where the block was broken properly, not just replaced, as the name suggests. 

That sounds like a separate event hook.

**Comment by Frontrider** [comment]
Simply setting the block is usually not enough to trigger that, specific event. I reserve place for when the block is placed normally.

I can give you an event that is running when the block is just set, without being placed.

**Comment by Nathan22211** [comment]
i'm not familiar with the changes you did in terms of the event command so that might help

**Comment by Frontrider** [comment]
https://github.com/CottonMC/FunctionAPI/wiki/Event-command

I added an event called `block/name/set` It will run when a command places the block. If it's the same function that you run when you place it by hand, then hook it up to both.

I'm not sure about triggering a place when a command does this. I don't want any uncertainties coming from a situation when there is no player around to provide rotation and things like that.

**Comment by Frontrider** [comment]
Internal mc things.

it is uploaded now, close the issue if it fixes it.
